### ISSUE TITLE
Add an example

### ISSUE THREAD

**Issue by seahindeniz** [warp-tech/russh#102]
Hi, could you add a working example directory for a client usage?

I'm a bit new to Rust and I got stuck with `can't find crate for 'russh_keys'`. A minimal repo or a directory which shows how use to this library, would be awesome, thanks

**Comment by Eugeny** [comment]
You can run the bundled examples from a source checkout with e.g.

```cargo run --example remote_shell_call 192.168.1.2:22 ~/.ssh/id_ed25519 'echo hello'```

The arguments for the `remote_shell_call` example are the host:port, private key path, command.

**Comment by Eugeny** [comment]
From your error message, it looks like you need to add `russh-keys` to your dependencies - it's a separate crate.
