### ISSUE TITLE
Can't establish SSH connection

### ISSUE THREAD

**Issue by DMaxter** [warp-tech/russh#103]
I can't establish an SSH connection using version v0.34.0

I have checked the examples, but they use `key::PublicKey` on the `check_server_key`  and it is private, so I couldn't find a way to approve my remote key.

**Comment by Eugeny** [comment]
russh_keys::key::PubilcKey [is not private](https://docs.rs/russh-keys/latest/russh_keys/key/enum.PublicKey.html)

**Comment by DMaxter** [comment]
My bad, it works now

Thank you
