### ISSUE TITLE
Unclear how to override `server::Handler` fns that use `session.channels`

### ISSUE THREAD

**Issue by alvaro-cuesta** [warp-tech/russh#105]
Basically what the title says. I'm just toying with Russh to learn its API but I realized copypasting the default `server::Handler` trait implementations is impossible since some of them use `session.channels` which is `pub(crate)` only.

E.g. the default `server::Handler::channel_eof` does this:

```rust
if let Some(chan) = session.channels.get(&channel) {
    chan.send(ChannelMsg::Eof).unwrap_or(())
}
```

It's also unclear _why_ this is there at all. Maybe I missed something but as far as I can tell `ChannelMsg::Eof` is not used anywhere else and I cannot do `chan.wait()` in my server code since I cannot access the channel in the first place?

Not sure if this is my fault and I'm missing something, or maybe there's some clarification missing the API docs.

**EDIT:** Is this the same as doing `session.handle().eof(channel_id)`? If so, could the default trait method implementations use the public interface instead? Maybe it's me but I think it's very common to copy-paste default implementations when implementing traits.

**EDIT2:** Something similar happens in `server::Handler::window_adjusted` which accesses `session.common`, also `pub(crate)`.

**EDIT3:** To clarify, this is while using v0.35.0-beta.8.

**Comment by Eugeny** [comment]
You can just call the default implementation directly like this:

```rust
let (self, session) = server::Handler::channel_eof(self, channel, session).await?;
```

The default implementations mostly just forward the messages to the individual `Channel` message queues which are accessible via `Channel::wait`

**Comment by alvaro-cuesta** [comment]
@Eugeny thank you for the prompt response.

Am I right to assume that messages on channels are just a convenience? E.g. being able to `Channel::wait` on `ChannelMsg::WindowChange` for a specific channel instead of implementing `server::Handler::window_change_request` and manually tracking `ChannelId`s myself.

I'm a bit confused though, how can I get a `Channel` from the server so I can `Channel::wait` on it?

I've been studying the docs and can only find `server::Handle::channel_open_session` returning a `Channel` on the server, but I'm trying to `Channel::wait` on a client-initiated channel.

Again thanks for the response and for forking Thrussh and improving on it ❤️

**Comment by Eugeny** [comment]
Correct! You can either use `Channel` or manually override the `Handler` methods instead. 

A `Channel` is passed to your `Handler` through various `channel_open_*` methods like this: https://docs.rs/russh/0.35.0-beta.8/russh/server/trait.Handler.html#method.channel_open_session

**Comment by michaelfortunato** [comment]
Just to be clear. I would call channel::wait in Server::Handler::channel_open_session? 
Thanks!

**Comment by Eugeny** [comment]
If you want to wait for channel messages, you can just spawn a new Tokio task to do so and pass your Channel to it - the Handler methods should not block, and if they do, you'll deadlock the connection.

**Comment by Eugeny** [comment]
From looking at it for a minute, the difference with your go library is that the go library spawns a new goroutine for each and every protocol request so that your handler never blocks, and russh doesn't, so you need to make the decision whether to spawn or not yourself

**Comment by michaelfortunato** [comment]
> If you want to wait for channel messages, you can just spawn a new Tokio task to do so and pass your Channel to it - the Handler methods should not block, and if they do, you'll deadlock the connection.

This makes sense to me. What I might do is spawn the Tokio task in `server::Handler::channel_open_session` or in one of the request handlers (`server::Handler::shell_request`). 
I am not sure which is best. As you pointed out, the go example spawns a go routine for each supported request type so I might go with spawning a Tokio task in shell_request.
