### ISSUE TITLE
Accessing channel input during exec_request

### ISSUE THREAD

**Issue by justinrubek** [warp-tech/russh#120]
I feel like I must be missing something, so I apologize if this is incredibly obvious. I've been trying everything I can think of for some time now.

I am trying to build a server that can be the target end of a `git push`. I originally thought it would be roughly enough to spawn a child process of `git-receive-pack` and connect the channel using [`copy_bidirectional`](https://docs.rs/tokio/latest/tokio/io/fn.copy_bidirectional.html). However it appears that I can never get any data from the channel.

To debug this, I started using `cat` so I could compare my application to OpenSSH. If I run `ssh localhost cat` (which goes to my OpenSSH daemon, not russh) I am able to type text and it is printed back to me, just like `cat` without ssh. When I try to replicate this inside `exec_request` though there is never any data read-- it just waits for data permanently. I've tried using `Channel::wait` as well as `Channel::into_stream` and using it as an `AsyncRead` but have had no luck with either.

My current `russh::server::Handler` is here https://github.com/justinrubek/thoenix/blob/aed91e27ddf80a05273b15ed7e59a9ef8c2fe1e9/crates/cli/src/main.rs#L284. Some of the code has gotten a bit messy as I've been messing with it a lot. I'd really appreciate some assistance, and would be willing to contribute another example if we get it working and that is desired.

**Comment by Eugeny** [comment]
The SSH client won't start sending stdin data packets until exec_request successfully completes - so you need to remember what command the client has sent - and then react to data packets in the future
