### ISSUE TITLE
Allow client to use reverse port forwarding `-R`

### ISSUE THREAD

**Issue by simao** [warp-tech/russh#126]
Hi,

I am trying to allow a client to open a reverse port on my server. I have something like this:

```rust
async fn tcpip_forward(
        self,
        address: &str,
        port: &mut u32,
        session: Session,
    ) -> Result<(Self, bool, Session), Self::Error> {
        let port = *port;
        let session_ref = &mut session;

        tokio::spawn(async move {
            let h = format!("127.0.0.1:{}", port);

            let listener = TcpListener::bind(h).await.unwrap();

            let (stream, addr) = listener.accept().await.unwrap();

            let chid = session_ref.channel_open_forwarded_tcpip(&addr.ip().to_string(),
                                                            addr.port() as u32,
                                                            &addr.ip().to_string(),
                                                            addr.port() as u32).unwrap();

            // TODO: then somehow use session.data(chid, data) to copy data from stream to session.data?
        });

        Ok((self, true, session))
    } 
```

But obviously this does cannot compile. Session cannot really be moved into the spawned async block, since we need to return it from `tcpip_forward`.

So is there a way to listen to a port on the server and forward that to a client? Or is this impossible at the moment? Should I be using something other than `Session` to open this channel?

Thanks

**Comment by Eugeny** [comment]
To avoid passing ownership of `Session` to your closure, you can instead take a session handle with `Session::handle()` and pass it instead:

```rust
async fn tcpip_forward(...) {
    let session_handle = session.handle();

    tokio::spawn(async move {
        let ch = session_handle.channel_open_forwarded_tcpip(...).await?;
        ch.data(...)?.await;
    });

    Ok((self, true, session))
} 
```

**Comment by simao** [comment]
Ah ok, I missed that.

Is there a way to also get data from that channel, so I can get data back to the stream as well?

Thanks

**Comment by Eugeny** [comment]
Yes - with [Channel::wait](https://docs.rs/russh/latest/russh/struct.Channel.html#method.wait)

**Comment by simao** [comment]
Actually I realised I can just use `into_stream` and then use that for `tokio::io::copy_bidirectional`, I think.

thanks a lot!
