### ISSUE TITLE
Initial window size

### ISSUE THREAD

**Issue by Kittenlover229** [warp-tech/russh#137]
Is there a way to access the initial size of an opened SSH terminal size (aka rows and columns) from the `russh::server::Handler`? 

There is a `window_change_request` method on the `russh::server::Handler`, but it is not invoked when a fresh connection is established. The arguments to `window_change_request` don't seem too clear either. Is `column_width` the width of a single column in pixels? Is the `pix_width` the width of the terminal in pixels, so the actual amount of columns is `pix_width / column_width`?

**Comment by Eugeny** [comment]
You can get the size when the client sends its initial PTY request (in https://docs.rs/russh/latest/russh/server/trait.Handler.html#method.pty_request). 

The terminal size is `column_width` x `row_height` characters - the `pix_width` and `pix_heights` fields, although part of SSH protocol, are rarely used by clients

**Comment by Kittenlover229** [comment]
That's very lovely! Just wondering, what are they (`pix_width` and `pix_heights`) actually used for? Not like SSH can set specific pixels afaik.

**Comment by Eugeny** [comment]
I've wondered that myself, but the RFC only says:

```
      uint32    terminal width, pixels (e.g., 640)
      uint32    terminal height, pixels (e.g., 480)
```

and 

> The character/row dimensions
   override the pixel dimensions (when nonzero).  Pixel dimensions refer
   to the drawable area of the window.
