### ISSUE TITLE
Connection timeout in client doesn't take effect

### ISSUE THREAD

**Issue by handewo** [warp-tech/russh#141]
```rust
 let config = client::Config {
        connection_timeout: Some(Duration::from_secs(5)),
        ..<_>::default()
 };
```
When I connect to a ssh server that is not existed, the time elapsed during connection with server is longer than `connection_timeout`.
Is it a useless field in `client::Config`?

**Comment by Eugeny** [comment]
The option is somewhat misleadingly named (`thrussh` legacy) - it's in fact the inactivity timeout after a live connection is closed. If you want to time out when setting up a connection, you can just use `tokio::time::timeout`. I'll keep this ticket open to rename the option later.

**Comment by handewo** [comment]
> misleadingly

I got it, but this option looks like doesn't  use anywhere.
