### ISSUE TITLE
Client Keyboard Interactive

### ISSUE THREAD

**Issue by joshbenz** [warp-tech/russh#142]
Do you have any suggestions for logging via keyboard interactive? I have a usecase for logging in via keyboard-interactive with the password. Does russh currently support something like that or is there changes that would need to be made to russh to facilitate such a usecase?

For example, Python's Paramiko attempts keyboard-interactive with the password if the normal password authentication fails. I imagine we don't want to do that, but it would be nice to have the methods to facilitate such a workflow when users implement the client. Or perhaps do what paramiko does

**Comment by joshbenz** [comment]
I totally missed this section in the docs https://docs.rs/russh/latest/russh/server/trait.Handler.html#method.auth_keyboard_interactive
Thank you for your awesome work!

**Comment by Eugeny** [comment]
Thanks - that's for the server-side code however, there's no support for K-I auth in the client yet :)

**Comment by joshbenz** [comment]
Yeah I realized that after I prematurely closed the issue HAH. Anyways, I'm a bit of a newbie but I would love to attempt to implement it when I get a chance!

**Comment by Eugeny** [comment]
Give it a try, I'll be happy to merge! Something to keep in mind API-wise is that keyboard-interactive authentication is special in a sense that a server can not only reply with "authenticated" or "rejected" but also with "I have some more questions for you".
