### ISSUE TITLE
Ability for server to support concurrent exec?

### ISSUE THREAD

**Issue by mwileczka** [warp-tech/russh#149]
Using the russh client (async_ssh2_tokio) I'm able to connect to an OpenSSH server and run multiple `exec` at the same time. For example, I can exec `sleep 20` first, then in a different tokio task, exec again on the same connection to run `uname -a` and it works just fine.

I'm trying to get the same thing working with the russh server. I've narrowed it down to server trait method `exec_request`, and honestly, a lot of the methods exhibit the same problem.

```
async fn exec_request(
        self,
        channel: ChannelId,
        data: &[u8],
        mut session: Session,
    ) -> Result<(Self, Session), Self::Error> {
```

The method has to return self and session, so session can't be moved or cloned to another task. If I run the shell command, get the output, send it back, send the exit code, and close the channel before I return, it works but it holds up all other execs from running.
I need the session (and ChannelId) so the shell output can be sent back after I spawn a task for it, but I can't figure out a way to do that.

I imagine you'd have the same problem for almost any of the other channel functions as well. For example, you start up an interactive `shell`, the request_shell would need to spawn a process and map the I/O, there is no possible way for it to finish before returning.

I apologize if I'm missing some Rust way of doing this, but I've been struggling with this for days and can't find any similar examples.

**Comment by Eugeny** [comment]
If you need to use the `Session` outside of the `Handler` methods, you can use [`Session::handle`](https://docs.rs/russh/latest/russh/server/struct.Session.html#method.handle) to grab a `Clone`able handle which you can use to send data etc.

**Comment by mwileczka** [comment]
Excellent, I finally got server working right. Might want to make that more explicit in the documentation, that solved a number of problems with async usage. Thank you!
