### ISSUE TITLE
The interactive ssh channel dead lock issue.

### ISSUE THREAD

**Issue by JohnGu9** [warp-tech/russh#159]
Consider the situation:
In the interactive ssh session, remote may send data to user at any time and user may send data to remote at any time.
In the code, the channel call ```request_shell``` api and become a interactive session. On the one hand, I need listen any data from channel at all time because I don't know when the data will arrive. But on the other hand, I need listen user input and forward data to channel. In rust, I need to lock the channel before I try to listen data from channel. But after I lock the channel, when I want to send data to channel and I also need to lock the channel. That cause dead lock.

**Comment by JohnGu9** [comment]
In rust ```future``` package, it provide ```split``` api that split a channel (for example tcpstream) into tx and rx that avoid this dead lock situation. I wonder  can russh's ```Channel``` provide the similar api?

**Comment by JohnGu9** [comment]
```rust
struct ChannelShareData {
    max_packet_size: u32,
    window_size: u32,
}

struct ChannelSender {
    sender: ChannelSender,
    _share_data: Arc<futures::lock::Mutex<ChannelShareData>>
}

struct ChannelReceive {
    receiver: UnboundedReceiver<OpenChannelMsg>,
    _share_data: Arc<futures::lock::Mutex<ChannelShareData>>
}

impl Channel {
    fn split() -> (ChannelSender, ChannelReceive);
}
```

**Comment by Eugeny** [comment]
You're right - this is currently a limitation of the `Channel` struct.

Currently, you can either implement an interruptible read loop like this:

```rust
let (tx, rx) = channel();

loop {
    tokio::select! {
        msg = channel.wait() {
            ...
        }
        action = rx.recv() {
            channel.do_something()
        }
    }
}
```

or obtain a session handle with `session.handle()` in one of your Handler methods (e.g. when you're getting a channel open event) and use `Handle::data` to send data without owning the `Channel`.

**Comment by JohnGu9** [comment]
Very thank for your answer, really great suggestion that I never thought before. Let me try some code. The ```wait``` return a not fusedfuture that ```select!``` refuse to accept. It seems to be a wrapper is required.

**Comment by JohnGu9** [comment]
Sorry, I didn't notice that there's ```select!``` in ```tokio``` package and just used the ```futures::select!```. Follow your suggestion  and ```tokio::select!``` work well.
