### ISSUE TITLE
Explicitly mentioning that Windows isn't supported

### ISSUE THREAD

**Issue by pieterdd** [warp-tech/russh#163]
This library currently isn't supported on Windows, is it? At least that's what I'm inferring from [this code block](https://github.com/warp-tech/russh/blob/master/russh-keys/src/agent/client.rs#L59-L64). If that's correct, it might be good to mention this explicitly in the README.

**Comment by Eugeny** [comment]
It's just the OpenSSH agent communication in the `russh-keys` crate that is not supported on Windows.
