### ISSUE TITLE
Commands executed at the start that i didn't send on ssh_client.execute

### ISSUE THREAD

**Issue by cybersoulK** [warp-tech/russh#194]
These commands run 30% of the time in the linux server, that match the creation of a russh client:
```tail, sshd, unix_chkpwd, setup-policy-ro, mkdir, mkdir, logger, logger, systemd-network, cat, logger, date, date, curl, logger, curl, date, date, logger, mkdir, grep, sed, ip, logger, date, date, curl, logger, curl, logger, date, date, curl, logger, curl, touch, cat, md5sum, md5sum, rm, mkdir, grep, ip, grep, sed, ip, logger, date, tail, sort, date, curl, logger, curl, mkdir, touch```

can you explain the reason why?

**Comment by Eugeny** [comment]
Do the same commands run when you launch an interactive shell (bash -i)...?

**Comment by cybersoulK** [comment]
not sure, i just use [async-ssh2-tokio](https://github.com/Miyoshi-Ryota/async-ssh2-tokio)
execute method, but it doesn't look like their github is spawning extra commands

**Comment by Eugeny** [comment]
This looks like the stuff that's running when your shell initializes and isn't in the scope of an ssh client

**Comment by cybersoulK** [comment]
you are right, i just double checked today 👍
