### ISSUE TITLE
Updating ed25519-dalek breaks agent server

### ISSUE THREAD

**Issue by gotlougit** [warp-tech/russh#198]
Hello, I've been using russh as the SSH implementation for [sshield](https://github.com/gotlougit/sshield), which aims to be a more secure SSH agent server. 

I was updating my dependencies and noticed that an upgrade for russh broke the agent. I bisected russh and found commit 43edc32f7b9fb9714ee5497cb2a85b37055394a7 was the culprit. Scanning the agent server code, I don't really see anything that would break the agent.

Running `ssh -T <sample-server>` with the updated russh gives me this output:

```
debug1: Found key in /home/gotlou/.ssh/known_hosts:2
debug1: rekey out after <redacted> blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after <redacted> blocks
debug1: get_agent_identities: ssh_fetch_identitylist: incomplete message
```

Whereas it should be:

```
debug1: Found key in /home/gotlou/.ssh/known_hosts:2
debug1: rekey out after <redacted> blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after <redacted> blocks
debug1: get_agent_identities: agent returned <redacted> keys
```

I think there is some issue with the way the russh agent sends the public keys to the ssh client, perhaps there was a conversion or two that was overlooked while upgrading to ed25519-dalek 2.0?

**Comment by Eugeny** [comment]
I think I might have found it - let me know if the fix works for you!

**Comment by gotlougit** [comment]
This fixed it, thank you very much!
