### ISSUE TITLE
Support `ecdsa-sha2-nistp256`

### ISSUE THREAD

**Issue by george-hopkins** [warp-tech/russh#201]
During building a custom ssh-agent client, I came across EC-DSA P256 host keys (`ecdsa-sha2-nistp256`). I extended `russh-keys` to support such keys with the help of [`p256`](https://crates.io/crates/p256). Is there a chance of merging support for such keys?

**Comment by Eugeny** [comment]
Yes, 💯 ! Looking forward to your pull request!

**Comment by robertabcd** [comment]
Can this be closed now as https://github.com/warp-tech/russh/pull/267 is merged?
