### ISSUE TITLE
Bind a Client to a Specific Interface

### ISSUE THREAD

**Issue by iwoloschin** [warp-tech/russh#217]
Is it possible to bind a client to a specific network interface or local address? I have a use case where I need to SSH to a IPv6 Link Local Address on not the default route. With `ssh` I can specify the interface with `-B eth1`, can russh do something similar?

**Comment by Eugeny** [comment]
No, that's currently not possible

**Comment by Eugeny** [comment]
Nevermind, I misunderstood your question. You can bind your own socket and use it together with [`client::connect_stream`](https://docs.rs/russh/latest/russh/client/fn.connect_stream.html)

**Comment by iwoloschin** [comment]
Ah, thanks!
