### ISSUE TITLE
Updating Cargo.toml Files to Reflect Cargo Version for Russh, Russh-Keys, etc...

### ISSUE THREAD

**Issue by judgeman5** [warp-tech/russh#220]
I notice that the Russh crate says the version of cargo it supports is 1.60>. I recently tried to build the crate with 1.63 and received compiler errors about using the stable version related to the, 'let....else' statements in .rs files under russh-keys. I notice that russh-keys does not have a cargo version. 

I'm hoping that this can either be addressed by taking out this russh-key syntax to support stable cargo version that Russh has in the cargo.toml (1.60>), or updating all Cargo.toml packages to correctly reflect the correct cargo versions supported.

**Comment by judgeman5** [comment]
I reverted back to 0.39 and made the appropriate changes and it compiled; however with version 0.40, there are a lot of crate dependencies that were added that require 1.65. Something to look into if you want to try and continue supporting Rust 1.60>. Will most likely need to downgrade some crates to the last version that used 1.60

**Comment by Eugeny** [comment]
I've updated the crates to explicitly indicate 1.65 as MSRV
