### ISSUE TITLE
`russh::server::run` does not listen to multiple `SocketAddr`s despite accepting them

### ISSUE THREAD

**Issue by samuela** [warp-tech/russh#223]
`russh::server::run` has the type
```
russh::server
pub async fn run<H, A>(config: Arc<Config>, addrs: A, server: H) -> Result<(), std::io::Error>
where
    H: Server + Send + 'static,
    A: ToSocketAddrs,
```
and can therefore be called with multiple addresses in its second argument. However, when provided with multiple `SocketAddr`s, it will only listen on the first one. For example,
```rs
#[tokio::main]
async fn main() {
  let addr1 = SocketAddr::from(([0, 0, 0, 0], 2222));
  let addr2 = SocketAddr::from(([0, 0, 0, 0], 3333));
  russh::server::run(Arc::new(Default::default()), [addr1, addr2], MyServer {}).await.unwrap();
}
```
will only respond to connections on 0.0.0.0:2222 and will not work on 3333:
```
❯ ssh -p 3333 sam@localhost 
ssh: connect to host localhost port 3333: Connection refused
```

**Comment by samuela** [comment]
I ended up tracking this down to https://docs.rs/tokio/latest/tokio/net/struct.TcpListener.html#method.bind:

> If addr yields multiple addresses, bind will be attempted with each of the addresses until one succeeds and returns the listener. If none of the addresses succeed in creating a listener, the error returned from the last attempt (the last address) is returned.

A confusing API imho...

**Comment by Eugeny** [comment]
This is [the same](https://doc.rust-lang.org/std/net/struct.TcpListener.html#method.bind) as the `std` listener. I'm going to leave it at that as it's trivial for the consumer to just resolve ToSocketAddrs directly and start multiple russh `Server`s - there's no shared state in the `Server` itself.
