### ISSUE TITLE
How to handle connections dropped due to `inactivity_timeout`?

### ISSUE THREAD

**Issue by samuela** [warp-tech/russh#229]
I'm spinning up `tokio::process::Command` for each connection to my server. I'm using [inactivity_timeout](https://docs.rs/russh/latest/russh/server/struct.Config.html#structfield.inactivity_timeout) to prune inactive connections. 

How can I kill a `tokio::process::Command` when its corresponding SSH connection has been dropped due to inactivity? AFAICT russh does not offer any means of notification when a connection has been dropped.

**Comment by Eugeny** [comment]
You can implement `Drop` for your `Handler` :)

**Comment by samuela** [comment]
Gotcha, thanks @Eugeny !
