### ISSUE TITLE
Channel doesn't expose adjust window size

### ISSUE THREAD

**Issue by mihirsamdarshi** [warp-tech/russh#25]
I was wondering whether I could expose the mechanism to send an adjust window size method on a client Channel, since RFC 4254 [does say that the client can also request a window size change](https://datatracker.ietf.org/doc/html/rfc4254#section-5.2)?

I was wondering if you could help me out with the structure of the code, if this was something you would be ok with me implementing?

I see that client has an [`adjust_window`](https://github.com/warp-tech/russh/blob/2fc70f6355a970a20c96bf4d24eeb8dac68a8f47/russh/src/client/mod.rs#L1549) method that is called internally when the window is adjusted. However, I have no clue what that does, since it just seems to return the parameter passed in un-touched. 

 In addition, the `Encrypted` struct has an [`adjust_window_size`](https://github.com/warp-tech/russh/blob/2fc70f6355a970a20c96bf4d24eeb8dac68a8f47/russh/src/session.rs#L159-L183) method which is used when the client receives data, but I am not sure whether this is the method that I should be calling, since it expects a slice of data (although I guess I could pass in an empty slice of u8).''

**Comment by Eugeny** [comment]
Hey! `russh` is a `thrussh` fork and the window size handling code is still original - so my interpretation might be incorrect.

The session code in `Session::client_read_authenticated` will call `Hander::adjust_window` after every received data or extended_data packet. With `adjust_window` being a trait method with a default impl, clients are free to override it and dynamically decide on the new window size after each received packet.

**Comment by mihirsamdarshi** [comment]
thanks!
