### ISSUE TITLE
Expected Performance

### ISSUE THREAD

**Issue by Disservin** [warp-tech/russh#257]
Hi,

I am a bit surprised by the time it takes it to run a command on the remote server, I
just took the example from "client_exec_simple" and added:
```rust
    let start = Instant::now();
    let code = ssh.call(&cmd.clone()).await?;
    let duration = start.elapsed();
    println!("Command '{}' finished in {:?}", cmd, duration);
```

Executing `uptime` on the server seems to take almost 400ms though...
`Command 'uptime' finished in 387.854669ms`, now executing it on the server it's almost instantaneous
```
 > time uptime
 21:18:11 up 10:03,  1 user,  load average: 0.16, 0.03, 0.01

real    0m0.002s
user    0m0.002s
sys     0m0.000s
```

What am I missing here or is this somewhat expected?

**Comment by Disservin** [comment]
Ah the `channel_open_session` takes a considerable amount of time to open, but somewhere I read that I can only use a channel once to send a command? So am I right that I would have to constantly reopen channels for every command that I'm sending or how can I speed this up, for subsequent calls?

**Comment by Eugeny** [comment]
Could you compare it with the output timing of ssh -v ... uptime? The ssh log shows when the channel is being opened too.

In general you can't reuse a channel for a second exec. You can request a shell and run multiple commands in it, but that's not a clean solution

________________________________

**Comment by Disservin** [comment]
I don't see many timings but at the end I can see a transfer duration
```
$ time ssh ... -v uptime
debug3: send packet: type 1
Transferred: sent 2904, received 2560 bytes, in 0.5 seconds
Bytes per second: sent 6355.4, received 5602.5
debug1: Exit status 0
ssh -i /home/max/.ssh/ec2_id_rsa  -vvv uptime  0.00s user 0.01s system 0% cpu 1.538 total
```
So that 0.5 seconds is the only timing I see from ssh.. so this is naturally taking quite some time... So I'm guessing I will have to use the shell workaround, do you have an example for that? Is it also possible to send a command, read the output, send another command etc.?

**Comment by Eugeny** [comment]
Yes, when using `request_shell`, you're basically exec'ing the user's default shell on the other side, and after that you simply get stdin/stdout for that shell, from which point on it's on you to figure out where one command's output ends and the next starts.

If you know what the output format it (e.g. 1 line per command), it's fairly easy to know. Or if you just need to run a batch of commands and get all the output, you can just submit them to the shell all at once.

**Comment by Disservin** [comment]
Alright, thanks for you help. I'll close this. 

Anything about: 
> perhaps you can also enable the discussion section instead of people having to discuss here in issues

**Comment by Eugeny** [comment]
> perhaps you can also enable the discussion section instead of people having to discuss here in issues

It's done :)
