### ISSUE TITLE
Missing ciphers

### ISSUE THREAD

**Issue by MrSpock** [warp-tech/russh#277]
Hi,
I'm trying to connect to some telco hardware that requires following configuration in ssh:
```
        KexAlgorithms +diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha1
        Ciphers +aes128-cbc,3des-cbc
        HostkeyAlgorithms +ssh-rsa
```
I was able to find respective key (`russh_keys::key::SSH_RSA`) however no way in finding ciphers.
My app exits with following error:
`
Error: SshError(NoCommonCipher)`

Such ssh config is very popular with a lot of telecommunication gear.

Is there a plan to add support for aes128-cbc,3des-cbc ?

**Comment by Eugeny** [comment]
Russh has the `dh-group1-sha1` kex, but not the `-cbc` ciphers. I don't plan to work on these, but PRs are welcome!

**Comment by Barre** [comment]
@Eugeny I guess this can be closed then!
