### ISSUE TITLE
Keepalive on client side

### ISSUE THREAD

**Issue by Dr-Shadow** [warp-tech/russh#29]
Hello,

Does russh support keepalive on the client side ?

Does it reply for us to the SSH server or do we have to do something ?

Thank you in advance

**Comment by Eugeny** [comment]
Hi, yes, currently keepalive is only implemented on the client side of the library.

IIRC the latest beta release will respond with REQUEST_FAILURE, while the master branch code responds to it with REQUEST_SUCCESS - however both are fine for OpenSSH servers.
