### ISSUE TITLE
TryFrom<PrivateKey> for KeyPair: RSA assumes SHA512

### ISSUE THREAD

**Issue by bjornhamra** [warp-tech/russh#292]
I was troubleshooting connections to legacy devices and I noticed russh currently fails to authenticate with rsa keys in my environment. 

I traced this down to `TryFrom<&PrivateKey> for KeyPair` which for rsa private keys will instantiate a new KeyPair with `SignatureHash::SHA2_512`. I'm in deep waters here, but it appears all the servers I interface with (dropbear) expect SHA256.

Doing the following fixed it for me:
```
diff --git a/russh-keys/src/format/openssh.rs b/russh-keys/src/format/openssh.rs
index c27a1bc..3da2d88 100644
--- a/russh-keys/src/format/openssh.rs
+++ b/russh-keys/src/format/openssh.rs
@@ -36,7 +36,7 @@ impl TryFrom<&PrivateKey> for KeyPair {
                 Ok(KeyPair::Ed25519(key))
             }
             KeypairData::Rsa(keypair) => {
-                KeyPair::new_rsa_with_hash(&keypair.into(), None, SignatureHash::SHA2_512)
+                KeyPair::new_rsa_with_hash(&keypair.into(), None, SignatureHash::SHA2_256)
             }
             KeypairData::Ecdsa(keypair) => {
                 let key_type = match keypair {
```

I'm unclear as to whether or not this is an actual bug or if I'm missing something fundamental. It looks to me like like all other ssh implementations (ones I have peeked at) default to SHA256 in RSA context.

Can someone with more domain knowledge shed some light on this? If it is indeed a bug and this is a valid fix (that doesn't break other things) I will gladly PR it.

**Comment by Eugeny** [comment]
Currently it's the same as OpenSSH which defaults to SHA-512 for `ssh-rsa` keys. You can swap the hash algorithm in the key using `KeyPair::with_signature_hash` after reading it.

**Comment by Eugeny** [comment]
No problem. The fingerprint is just a hash of the public key - the public key auth algorithm is independent from that.
