### ISSUE TITLE
`russh::server::Server::handle_session_error` seems to reference the new client instance rather than the one with the failed session

### ISSUE THREAD

**Issue by unrenamed** [warp-tech/russh#293]
I'm developing an SSH chat server based on the [`russh::server`](https://docs.rs/russh/latest/russh/server/index.html) API. Currently, I'm looking for a way to handle situations where a user closes their terminal or powers off their device, so the server can remove the client from the list of chat members. [`russh::server::Server::handle_session_error`](https://docs.rs/russh/latest/russh/server/trait.Server.html#method.handle_session_error) seems to be the appropriate method for this.

However, after running some tests, I noticed strange behavior. When `handle_session_error` is called, it references (`&mut self`) the new client with the new client ID instead of the one with the failed session.

Here's a simplified version of the example code from the library (i.e., a Ratatui app with all the rendering logic removed, as it's not important). You can see how methods from the Handler trait contain the expected client ID, while `handle_session_error` appears to reference a clone of the client created earlier.

```rust
use std::collections::HashMap;
use std::sync::Arc;

use async_trait::async_trait;
use russh::server::*;
use russh::{Channel, ChannelId};
use tokio::sync::Mutex;

struct App {}

impl App {
    pub fn new() -> App {
        Self {}
    }
}

#[derive(Clone)]
struct AppServer {
    clients: Arc<Mutex<HashMap<usize, App>>>,
    id: usize,
}

impl AppServer {
    pub fn new() -> Self {
        Self {
            clients: Arc::new(Mutex::new(HashMap::new())),
            id: 0,
        }
    }

    pub async fn run(&mut self) -> Result<(), anyhow::Error> {
        tokio::spawn(async move {
            loop {
                tokio::time::sleep(tokio::time::Duration::from_secs(1)).await;
                // here is the render logic
            }
        });

        let config = Config {
            inactivity_timeout: Some(std::time::Duration::from_secs(3600)),
            auth_rejection_time: std::time::Duration::from_secs(3),
            auth_rejection_time_initial: Some(std::time::Duration::from_secs(0)),
            keys: vec![russh_keys::key::KeyPair::generate_ed25519().unwrap()],
            ..Default::default()
        };

        self.run_on_address(Arc::new(config), ("0.0.0.0", 2222))
            .await?;
        Ok(())
    }
}

impl Server for AppServer {
    type Handler = Self;
    fn new_client(&mut self, _: Option<std::net::SocketAddr>) -> Self::Handler {
        let s = self.clone();
        self.id += 1;
        println!("new_client: id = {}", self.id);
        s
    }

    fn handle_session_error(&mut self, _error: <Self::Handler as Handler>::Error) {
        println!("handle_session_error: id = {}", self.id);
        eprintln!("handle_session_error: {}", _error);
    }
}

#[async_trait]
impl Handler for AppServer {
    type Error = anyhow::Error;

    async fn channel_close(&mut self, _: ChannelId, _: &mut Session) -> Result<(), Self::Error> {
        println!("channel_close: id = {}", self.id);
        Ok(())
    }

    async fn channel_eof(&mut self, _: ChannelId, _: &mut Session) -> Result<(), Self::Error> {
        println!("channel_eof: id = {}", self.id);
        Ok(())
    }

    async fn channel_open_session(
        &mut self,
        _: Channel<Msg>,
        _: &mut Session,
    ) -> Result<bool, Self::Error> {
        {
            println!("channel_open_session: id = {}", self.id);
            let mut clients = self.clients.lock().await;
            let app = App::new();
            clients.insert(self.id, app);
        }

        Ok(true)
    }

    async fn auth_none(&mut self, _: &str) -> Result<Auth, Self::Error> {
        Ok(Auth::Accept)
    }

    async fn data(
        &mut self,
        channel: ChannelId,
        data: &[u8],
        session: &mut Session,
    ) -> Result<(), Self::Error> {
        println!("data: id = {}", self.id);
        match data {
            // Pressing 'q' closes the connection.
            b"q" => {
                self.clients.lock().await.remove(&self.id);
                session.close(channel);
            }
            _ => {}
        }

        Ok(())
    }
}

#[tokio::main]
async fn main() {
    let mut server = AppServer::new();
    server.run().await.expect("Failed running server");
}
```

To reproduce the issue, simply run the server, connect to it via **`ssh -p 2222 user@127.0.0.1`**, and then close the terminal window/tab you run this command from.

The actual result is:
<img width="748" alt="image" src="https://github.com/warp-tech/russh/assets/32395926/ea663d41-72d1-45ad-9b49-67b49e2c6e85">

I expected to see:
```
channel_open_session: id = 0
handle_session_error: id = 0
handle_session_error: early eof
```
since `0` is the ID of the user saved to the list and it's the only user online that suddenly left the chat.

There are two main questions:
1. Is the described behavior expected?
1. If yes, how would you suggest handling an unexpected terminal closure (e.g., killed by the OS, closed manually by the user, etc.) then?

**Comment by Eugeny** [comment]
It's because you're conflating `Server` with `Handler`. You should have separate structs that implement these traits. Russh works with one `Server` instance and multiple `Handler`s. 

`handle_session_error` is a `Server` method and you're seeing your own self-incremented `<self as Server>::id`.

**Comment by Eugeny** [comment]
In case you've used `echoserver` example as the base for your code, that's on me as `echoserver` omits having separate structs to keep the code shorter :v:

**Comment by unrenamed** [comment]
@Eugeny, thanks for the quick reply.

> It's because you're conflating Server with Handler.

You are right, I am. Now that you said that the traits descriptions make more sense to me.

 > In case you've used echoserver example as the base for your code
 
[`ratatui_app`](https://github.com/warp-tech/russh/blob/main/russh/examples/ratatui_app.rs) is the one I used as a reference since it was the most suitable to my use case. I understand the urge to keep the code shorter in the examples, but in my case this led to confusion. I'm not suggesting anything though, just sharing my experience with the lib.

**Comment by unrenamed** [comment]
@Eugeny, I think having separate structs that implement `Server` and  `Handler` traits might not be acceptable for my use case yet. I've just realized the server runs an infinite loop that renders the view to the connected clients (each client has own terminal handle, of course). This is exactly what [`ratatui_app`](https://github.com/warp-tech/russh/blob/main/russh/examples/ratatui_app.rs) does and perhaps this explains the reason behind implementing both traits for one struct, i.e. `AppServer`. What do you think?

**Comment by Eugeny** [comment]
Even in this case, you still don't need it to be the same structure. The [busy loop](https://github.com/warp-tech/russh/blob/main/russh/examples/ratatui_app.rs#L74-L100) does not even reference `self` (beyond using the shared `clients` `Arc`)
