### ISSUE TITLE
Support custom server_id line terminators.

### ISSUE THREAD

**Issue by evilsocket** [warp-tech/russh#34]
Hi, I opened this [same issue on the original thrussh repo](https://nest.pijul.com/pijul/thrussh/discussions/51) but it was never fixed/implemented, trying again here before I go creating my own fork just for this small change.

I’m using thrussh to create an SSH server honeypot. Among the configuration options, the user can specify the server_id (which is basically what nmap and most of the tools use to fingerprint the SSH server). The problem is that some banners are terminated by a single “\n”, while others are terminated by “\r\n”, but the library hardcodes the latter here https://github.com/warp-tech/russh/blob/master/russh/src/sshbuffer.rs#L40-L44

If someone passes a banner like “something\n”, that breaks the protocol because “\r\n” is added anyway. You can find more details about this issue here https://github.com/evilsocket/medusa/issues/3

I suggest to add the server_id termination bytes as a configurable option (default to “\r\n”). Let me know if you prefer to do the changes yourself or you’d prefer me sending a PR ^_^

**Comment by Eugeny** [comment]
Hi, the RFC says that `\r\n` is explicitly required and only some older undocumented implementations used `\n`. I won't be able to find time to spend on such quirks, but will accept a PR changing the type of `server_id` to something along the lines of

```rust
enum ServerID {
  Normal { software: String, version: String },
  Raw(String)
}
```
