### ISSUE TITLE
At which point is it possible to send a prompt to the client in a Server implementation?

### ISSUE THREAD

**Issue by evilsocket** [warp-tech/russh#35]
Hi (again), I've tried to read the docs and the code but still failed in my intent. I'm implementing an honeypot server and I want to send a fake shell prompt (or any other string) to new clients as soon as they start the session, before they start sending commands.

I've tried here since it's one of the few points where the Session object is mutable, but the client never displays it https://github.com/evilsocket/medusa/blob/main/src/protocols/ssh/handler.rs#L214 while it works fine in the data handler and/or after an exect_request.

Thanks

**Comment by Eugeny** [comment]
You need to wait for the client to complete the channel set up - i.e. wait for either `shell_request` or `exec_request` on that channel.

**Comment by Eugeny** [comment]
The session is passed to you by value, you can just make the argument mutable at https://github.com/evilsocket/medusa/blob/main/src/protocols/ssh/handler.rs#L231, or alternatively grab an async session handle first through https://docs.rs/russh/0.34.0-beta.13/russh/server/struct.Session.html#method.handle which controls a session remotely without owning it.

**Comment by evilsocket** [comment]
worked perfectly, thanks a lot
