### ISSUE TITLE
russh-keys 0.22.0-beta.6 doesn't seem to include changes

### ISSUE THREAD

**Issue by connor4312** [warp-tech/russh#42]
russh-keys `0.22.0-beta.6` was published after my change in https://github.com/warp-tech/russh/commit/e15d2cea97a9e2908e0bd0f7f65e3ce9906796c7 ([history](https://github.com/warp-tech/russh/commits/master/russh-keys)) but the crate doesn't seem to actually include the changes to add `impl Default`:

![](https://memes.peet.io/img/22-09-167305e6-abad-41cc-9d84-a82c0b70f96d.png)

I think something went wrong in the publishing process

**Comment by Eugeny** [comment]
Whoops, v0.22.0-beta.7 is out now!
