### ISSUE TITLE
"No common key algorithm" error when connect to ssh server

### ISSUE THREAD

**Issue by ChenhuiZhang** [warp-tech/russh#45]
Hello,

I try the example code in async-ssh2-tokio ([link](https://lib.rs/crates/async-ssh2-tokio)), but failed with below error:

Error: Other Error Happen

Caused by:
    No common key algorithm

The server is ok as I can ssh it by "ssh" command in linux, and if I try the same code to ssh a raspberry pi, it also works.  I searched in google, and try to compare the difference :

When check the key_exchange_init message in wireshark:

for my unit:
**server_host_key_algorithms string: rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256**

for raspberry pi:
**server_host_key_algorithms string: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519**

So it seems there is something different, does anyone know what was wrong? How can I fix it in the client side? 

Best Regards,
Hermes

**Comment by ChenhuiZhang** [comment]
The version I used:

61-[[package]]
62:name = "async-ssh2-tokio"
63-version = "0.2.1"
64-source = "registry+https://github.com/rust-lang/crates.io-index"
65-checksum = "32ff28461c417d0b8a8b41c128a85abdf9de0907d0b6e3a698b7b74da46ed8af"
66-dependencies = [
67: "russh",
68: "russh-keys",
69- "thiserror",
70-]
71-
--
790-]
791-
792-[[package]]
793:name = "russh"
794-version = "0.34.0-beta.16"
795-source = "registry+https://github.com/rust-lang/crates.io-index"
796-checksum = "43a47850d2711f53330077c1ca72f7f326ec1658b68add7dbc22c384731b6adb"

**Comment by amtelekom** [comment]
The rsa keys [are dependent](https://github.com/warp-tech/russh/blob/master/russh/src/key.rs#L32) on the `openssl` feature (could probably be improved in the docs),
and (as stated in the [Readme](https://github.com/warp-tech/russh/blob/master/README.md)) the only other supported host_key is `ssh-ed25519`, which your "unit" doesn't seem to offer.

**Comment by ChenhuiZhang** [comment]
Hi amtelekom,

Really appreciate your info, Yes, after enable the "openssl" feature, it works. Thanks.

Best Regards,
Hermes
