### ISSUE TITLE
No disconnect handler when using exec_request

### ISSUE THREAD

**Issue by AviiNL** [warp-tech/russh#85]
Behavior is different when using `exec_request` over a "normal" connection
```
$ ssh localhost -p2222 test
```
vs
```
$ ssh localhost -p2222
```

When adding the test parameter (which will be put into an `exec_request`) data isn't received per-keystroke anymore, but only once per new-line, and a ctrl+c on the client side doesn't trigger disconnects or channel close or anything.

How or when do I know on the server when a client closed / disconnected the session when they supply an argument using `exec_request`?

**Comment by Eugeny** [comment]
P.S. ctrl-c will send a [signal](https://docs.rs/russh/latest/russh/server/trait.Handler.html#method.signal) instead when no PTY is allocated

**Comment by AviiNL** [comment]
Thanks for the quick response! :)

I am logging signals using
```
fn signal(self, channel: ChannelId, signal_name: russh::Sig, session: Session) -> Self::FutureUnit {
    info!("Signal: {} {:?}", channel, signal_name);
    self.finished(session)
}
```
but nothing is coming in, the ssh client just drops back to shell..

Unfortunately because of current (already running) client implementations I can't add a `-t` to the client requests.

I'm working on re-writing my personal proxy server from typescript to rust, so I can't change how to the clients interacts with the server.

I would at the very least expect a `channel_close` when a client disconnects, since a channel is opened via `channel_open_session`, Or am I misunderstanding how this should work?

**Comment by Eugeny** [comment]
It's possible that your client just kills the connection without sending a signal or a `channel_close` message - in this case you can implement `Drop` for your handler - russh will `drop` it when the connection ends.

**Comment by AviiNL** [comment]
Hah. how did I not think of that.
Yes, implementing drop does trigger when the client disconnects.

Thanks a bunch! :D
