### ISSUE TITLE
Native support for subsystems

### ISSUE THREAD

**Issue by AspectUnk** [warp-tech/russh#89]
Would you like to add native support for subsystems such as SFTP and etc.? At the moment, the lib does not provide simple "out-of-the-box" implementations of server-side and client-side subsytems. I could take the time to integrate my ready implementation under russh, since I have already taken the time to implement the SFTP protocol on the server side. Are you interested in PR?

**Comment by Eugeny** [comment]
Hey, sounds great! I've recently added an [AsyncWrite/AsyncRead wrapper for client channels](https://docs.rs/russh/latest/russh/struct.ChannelStream.html) and will be adding one for server channels soon - so I think the best way forward is for your library to accept generic `AsyncRead/-Write` streams (IIRC SFTP doesn't use other SSH protocol messages such as signals?). 

This will allow using it with russh clients immediately and with servers as soon as I add server-side `ChannelStream`, while also leaving it open to be compatible with potential other SSH libs!

We could also later add a simple "subsystem interface", e.g. `Session::register_subsystem(name: &str, handler: |stream: AsyncRead + AsyncWrite| -> Future)`

**Comment by AspectUnk** [comment]
> (IIRC SFTP doesn't use other SSH protocol messages such as signals?).

Yes, this protocol follows a simple request-response data model

> This will allow using it with russh clients immediately and with servers as soon as I add server-side `ChannelStream`, while also leaving it open to be compatible with potential other SSH libs!

Let me know about any updates

> We could also later add a simple "subsystem interface", e.g. `Session::register_subsystem(name: &str, handler: |stream: AsyncRead + AsyncWrite| -> Future)`

Great idea! This will integrate it simply and without horrible implementations. I think I can do it soon.

**Comment by AspectUnk** [comment]
> I've recently added an [AsyncWrite/AsyncRead wrapper for client channels](https://docs.rs/russh/latest/russh/struct.ChannelStream.html)

So, I looked into what you provided and I don't fully understand how this is supposed to help. The basic idea was to add an additional handler (such as `russh::client::Handler` but for the subsystem) for sftp packets

**Comment by Eugeny** [comment]
Hey, no problem! My idea was that on your side, your SFTP implementation doesn't have to depend on `russh`, but can simply expect _any_ AsyncRead/Write stream instead. To use it with `russh`, one would open a subsystem channel, wrap it into a `ChannelStream` and hand it off to your library. 

You can then design the library however you like (your own Handler trait, events, etc) since you'll have the full control over the channel.

**Comment by AspectUnk** [comment]
I went back to the problem. Apparently I don't understand something.
```
let mut channel = session.channel_open_session().await?;
println!("=== after open channel");

channel.request_subsystem(true, "sftp").await?;

let session = Arc::new(session);
let (mut stream, _sender) = ChannelStream::new(channel.id(), session.clone());

// server receives data
stream.write_u32(1).await?;

let mut buffer = [0; 4];
let n = stream.read(&mut buffer[..]).await?; // data comes in client::Handler fn data, but cannot be read here
println!("{:?}", n);
```

**Comment by Eugeny** [comment]
No problem, you're very close! `Handler::data` actually has a [default implementation that forwards data packets to individual Channel handles (and by extension, ChannelStreams)](https://github.com/warp-tech/russh/blob/master/russh/src/server/mod.rs#L440-L447) - so you just need to either not implement `Handler::data`, or call its default implementation from your implementation

**Comment by AspectUnk** [comment]
I did a little research on the `ChannelStream` code and also looked at [this comment](https://github.com/warp-tech/russh/pull/49#issuecomment-1276483748). After creating ChannelStream it returns [UnboundedSender which should be put into HashMap](https://github.com/microsoft/dev-tunnels/blob/b20ef08c719f843a1d9ba8610c52071fae6a482f/rs/src/connections/relay_tunnel_host.rs#L196-L199) and when [receiving data in client::Handler::data it is sent to all by this HashMap](https://github.com/microsoft/dev-tunnels/blob/b20ef08c719f843a1d9ba8610c52071fae6a482f/rs/src/connections/relay_tunnel_host.rs#L931-L933).

You said that the default implementation of client::Handler::data should send the data, but this is impossible for two reasons.

The first reason is in the default client::Handler::data implementation, the function sends data to [only one UnboundedSender that finds it first](https://github.com/warp-tech/russh/blob/5b6186ddf366e9f6aaba2fe743e024bfdc573406/russh/src/client/mod.rs#L1349), but the idea is that after creating a ChannelStream there should already be several in the HashMap, default and new from the ChannelStream.

The second reason is that [access to client::Session:channels is hidden](https://github.com/warp-tech/russh/blob/5b6186ddf366e9f6aaba2fe743e024bfdc573406/russh/src/client/mod.rs#L135), and UnboundedSender is not added to the channels HashMap. Since you said about the default implementation I assume it must be added to client::Session:channels after creation.

Is it really a mistake or am I missing something? Correct me if I'm wrong

**Comment by AspectUnk** [comment]
Looks good. Thank you @Eugeny  for taking the time to do this.

Can you share plans about rework and how you envision implementing `ChannelStream` for the server? What do you think needs to be done to have this in the beta? I would like to help you with the implementation of this.

I think it would be a good idea to move the ChannelStream discussion to another issue. Please do so if necessary.

Question about sftp lib. Can I add another member to the workspace? Like russh-sftp. You could publish it as crate. I could do it myself, but I can hardly support and work on issue, PR and etc.

**Comment by Eugeny** [comment]
Thanks for checking! I've got part (passing `Channel<Msg>` to the Handler instead of `ChannelId`) of the work done in #48, but it needs testing & verification - would be awesome if you could with this as I'm short on time right now.

If that works, `into_stream` should theoretically work as well - I haven't tested it yet.

As said, I prefer if the SFTP implementation doesn't become `russh`-specific, hence the whole AsyncRead/Write compatibility story. I also know absolutely nothing about the SFTP protocol, so I won't be able to meaningfully maintain it.

**Comment by AspectUnk** [comment]
@Eugeny thanks for what you do for the community and for me! We need to coordinate work on future things :_D

How soon will you release a new beta version? If you need help, do not hesitate to tag me, I'll be happy to support you if it's possible for me

This month I will publish a crate for SFTP support. What are your thoughts on adding a list of custom additions to the readme in the future?

**Comment by Eugeny** [comment]
Thank you so much, it means a lot! 

I usually release betas whenever I need to update russh in Warpgate or whenever somebody asks - do you need a fresh one? 

I'll be happy to add SFTP to the docs and examples of course

**Comment by AspectUnk** [comment]
Okay, then I won't close this issue until the first few versions of sftp crate. And yes, please release the current master as russh beta 7

**Comment by Eugeny** [comment]
Done

**Comment by AspectUnk** [comment]
I published a crate but only for the server side. Published as `russh-sftp` because the implementation cannot be used anywhere else as I have not seen any other ssh2 with server. I also added an example of a [simple server](https://github.com/AspectUnk/russh-sftp/blob/master/examples/server.rs) and roadmap if you're wondering what work will still be done this month
