### ISSUE TITLE
Unable to connect to server with only public key authentication allowed

### ISSUE THREAD

**Issue by hwittenborn** [warp-tech/russh#90]
Whenever I try to create an SSH server with only public key authentication allowed, I always get a `Permission denied (publickey)` message from `ssh`. I was able to reproduce the situation with the following code:

```rust
use core::pin::Pin;
use futures::FutureExt;
use russh::{
    server::{self, Auth, Session},
    MethodSet,
};
use russh_keys::key::{KeyPair, PublicKey};
use std::{net::SocketAddr, str::FromStr, sync::Arc};

#[derive(Clone)]
struct Server {}

impl server::Server for Server {
    type Handler = Self;

    fn new_client(&mut self, socket_addr: Option<SocketAddr>) -> Self {
        self.to_owned()
    }
}

impl server::Handler for Server {
    type Error = russh::Error;
    type FutureAuth =
        Pin<Box<dyn core::future::Future<Output = Result<(Self, Auth), Self::Error>> + Send>>;
    type FutureUnit =
        Pin<Box<dyn core::future::Future<Output = Result<(Self, Session), Self::Error>> + Send>>;
    type FutureBool = Pin<
        Box<dyn core::future::Future<Output = Result<(Self, Session, bool), Self::Error>> + Send>,
    >;

    fn finished_auth(self, auth: Auth) -> Self::FutureAuth {
        async move { Ok((self, auth)) }.boxed()
    }

    fn finished_bool(self, b: bool, session: Session) -> Self::FutureBool {
        async move { Ok((self, session, b)) }.boxed()
    }

    fn finished(self, session: Session) -> Self::FutureUnit {
        async move { Ok((self, session)) }.boxed()
    }

    fn auth_publickey(self, user: &str, public_key: &PublicKey) -> Self::FutureAuth {
        async move { self.finished_auth(Auth::Accept).await }.boxed()
    }
}

#[tokio::main]
async fn main() {
    let mut config = server::Config::default();
    config.methods = MethodSet::PUBLICKEY;
    config.keys.push(KeyPair::generate_ed25519().unwrap());

    server::run(
        Arc::new(config),
        &SocketAddr::from_str("0.0.0.0:2222").unwrap(),
        Server {},
    )
    .await
    .unwrap();
}
```

If I add a `println!("AUTH PUBKEY BEING CALLED");` line right below the function declaration at `fn auth_publickey(self, user: &str, public_key: &PublicKey)`, my terminal doesn't show any output, leading me to think the function is never even being called, but I can't figure out why that might be the case.

**Comment by Eugeny** [comment]
Hi, are you using OpenSSH as the client? In this case, it might not even try pubkey authentication depending on the `PubkeyAcceptedKeyTypes` option. Try `-o PubkeyAcceptedKeyTypes=+ssh-rsa`. 

Russh supports `rsa-sha2-256/512` signature types, but doesn't support the OpenSSH protocol extension to announce them yet, so OpenSSH clients can decide not to use it.

**Comment by hwittenborn** [comment]
I just tested with the `-o` stuff and can confirm it worked after that. How long do you think it might be until the OpenSSH protocol extension stuff you were talking about might be added? I'd be willing to look into contributing the needed code too if you could guide me to a place where I could figure out how to implement it.

**Comment by Eugeny** [comment]
I've already committed it but haven't released a new beta yet, it would be fantastic if you could give it a try

**Comment by hwittenborn** [comment]
Yeah I'd be fine with trying it - What branch/commit should I set my project to pull from?

**Comment by Eugeny** [comment]
master

**Comment by hwittenborn** [comment]
Sorry for the delay @Eugeny, but I can confirm it's all working when building from `master`. Feel free to close the issue whenever you feel it's appropriate.

**Comment by Eugeny** [comment]
Thank you for checking!
