### ISSUE TITLE
Weird issue when sending a message from a server on an SSH connection

### ISSUE THREAD

**Issue by hwittenborn** [warp-tech/russh#92]
I'm using this library's server portion, and the following code for the `Handler` trait is producing some weird output:

```rust
fn shell_request(self, channel: ChannelId, mut session: Session) -> Self::FutureUnit {
    session.data(channel, "Interactive shell is disabled.\n".to_string().into());
    session.close(channel);
    self.finished(session)
}
```

For some reason this is showing the following output in my terminal when connecting to the server:

```
Interactive shell is disabled.
                              Connection to dev.hunterwittenborn.com closed.
```

I'm not sure how related to the library this is, but any idea what might be causing it?

**Comment by Eugeny** [comment]
What is it specifically about this output that raises a question?

**Comment by hwittenborn** [comment]
The indentation on the second line isn't there when I connect to other SSH servers, that's not supposed to be there right?

**Comment by hwittenborn** [comment]
I can confirm the `\r\n` stuff fixed the issue, thanks! :)

**Comment by michaelfortunato** [comment]
Yes I experience the same issue. Could you tell me the best way to provide pty comparable output? What I am doing now is switching on \r and replacing that with \r\n.

In other words, what's happening is that the server is interpreting my client key press \n as \r. Is this to be expected?
