### ISSUE TITLE
Track request from `auth_publickey` function

### ISSUE THREAD

**Issue by hwittenborn** [warp-tech/russh#94]
Sorry for yet another issue :p. There's just some more stuff I had a question about, and something I wasn't sure if the library was capable of solving or not.

---

In my application, users can pull Git repositories like you can on GitHub, and one of the available methods for doing such is via SSH. I'm wanting to identify users via their SSH keys, and I thus have a setup somewhat like this:

```rust
struct Server {}

impl server::Handler for Server {
    fn auth_publickey(self, _user: &str, _public_key: &russh_keys::key::PublicKey) -> Self::FutureAuth {
        self.finished_auth(Auth::Accept)
    }
    fn exec_request(self, channel: ChannelId, data: &[u8], mut session: Session) -> Self::FutureUnit {
        /* What here? */
    }
}
```

I'm needing some kind of way to track a fingerprint to the current session, so that I can map a fingerprint to a user inside of `fn exec_request`. Is there any way a session could be passed into `fn auth_publickey` so that I could just enter vectors of `(Session::id(), PublicKey)` pairs into my struct?

**Comment by Eugeny** [comment]
You can just implement server::Handler on a separate struct, e.g.:

```rust

impl server::Server for Server {
    type Handler = SomeSession;
    fn new_client(&mut self, _: Option<std::net::SocketAddr>) -> SomeSession {
        SomeSession { key_fingerprint: None }
    }
}

struct SomeSession {
	key_fingerprint: Option<String>
}

impl server::Handler for Server {
    fn auth_publickey(self, _user: &str, _public_key: &russh_keys::key::PublicKey) -> Self::FutureAuth {
        self.key_fingerprint = Some(...);
        self.finished_auth(Auth::Accept)
    }
}```

**Comment by hwittenborn** [comment]
Thanks for the response! I can confirm it works with the stuff you recommended, thanks a ton for the help!
