### ISSUE TITLE
client channel extended data AsyncReader

### ISSUE THREAD

**Issue by mllken** [warp-tech/russh#99]
Hi,

I'm really liking the new async trait handlers!

I can turn a channel into a AsyncRead + AsyncWrite stream using Channel's into_stream() method.  Could you also provide a method to stream a Channel's stderr?  Possibly, it could be a AsyncReader for extended data for the channel, special cased for where the extended_code == 1.  

I'm using russh-0.35.0-beta.8
Thanks

**Comment by Eugeny** [comment]
Now available in v0.39.0-beta.1
